meu_projeto_dbt:
  outputs:
    dev:
      type: postgres
      host: db
      user: dbt_user
      password: dbt_password
      port: 5432
      dbname: dbt_database
      schema: public
      threads: 1
  target: dev
